remote_theme: pmarsceill/just-the-docs


title: PDF Lecture Notes
baseurl: "/pdf"
url: "https://notes.sibeliusp.com"
permalink: pretty

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: loo
footer_content: "Copyright &copy; 2017-2021 Sibelius Peng."
